general_data:
  hh_marg_file: "../processed_data/full/hh_marginals_full.csv"
  p_marg_file: "../processed_data/full/pp_full_marginals.csv"
  hh_sample_file: "../processed_data/full/hh_sample_ipu.csv"
  p_sample_file: "../processed_data/full/pp_sample_ipu.csv"







