- method: ipf
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_sample_file: "../processed_data/full/HH_sample_ipu.csv"
  hh_seed_data: "../processed_data/full/HH_sample_ipu.csv"
  level: "hh"
  zone_field: "zone_id"
  output_name: "ipf_normal"
  hh_syn_name: "hh_syn_ipf_normal.csv"
  reruns: 10

- method: ipf
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_sample_file: "../processed_data/full/HH_pool.csv"
  hh_seed_data: "../processed_data/full/HH_sample_ipu.csv"
  level: "hh"
  zone_field: "zone_id"
  output_name: "ipf_bn"
  hh_syn_name: "hh_syn_ipf_bn.csv"
  reruns: 10

- method: bn
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_seed_data: "../processed_data/full/HH_sample_ipu.csv"
  hh_sample_file: "../processed_data/full/HH_pool.csv"
  level: "hh"
  retrain: False
  zone_field: "zone_id"
  output_name: "bn"
  hh_syn_name: "hh_syn_bn.csv"
  reruns: 10

- method: wgan
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_seed_data: "../processed_data/full/HH_sample_ipu.csv"
  hh_sample_file: "../processed_data/full/wgan_pool.csv"
  level: "hh"
  zone_field: "zone_id"
  output_name: "wgan"
  hh_syn_name: "hh_syn_wgan.csv"
  reruns: 10