# - method: ipu
#   hh_marg_file: "../processed_data/full/hh_marginals_full.csv"
#   p_marg_file: "../processed_data/full/pp_full_marginals.csv"
#   hh_sample_file: "../processed_data/full/hh_sample_ipu.csv"
#   p_sample_file: "../processed_data/full/pp_sample_ipu.csv"
#   output_name: "ipu_full"
#   hh_syn_name: "hh_syn_ipu.csv"
#   pp_syn_name: "pp_syn_ipu.csv"
#   stats_name: "stats_ipu.csv"

# - method: ipu
#   hh_marg_file: "../processed_data/small/hh_marginals_small.csv"
#   p_marg_file: "../processed_data/small/pp_small_marginals.csv"
#   hh_sample_file: "../processed_data/small/hh_sample_ipu.csv"
#   p_sample_file: "../processed_data/small/pp_sample_ipu.csv"
#   output_name: "ipu_small"
#   hh_syn_name: "hh_syn_ipu.csv"
#   pp_syn_name: "pp_syn_ipu.csv"
#   stats_name: "stats_ipu.csv"

- method: saa
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_sample_file: "../processed_data/full/HH_pool.csv"
  hh_seed_data: "../processed_data/full/hh_sample_ipu.csv"
  level: "hh"
  zone_field: "zone_id"
  considered_atts:
    - hhsize
    - hhinc
    - totalvehs
    - dwelltype
    - owndwell
  ordered_to_adjust_atts:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  last_adjustment_order:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  max_run_time: 15
  extra_rm_frac: 0.3
  randomly_add_last:
    - hhinc
  output_each_step: True
  add_name_for_step_output: "BN"
  include_zero_cell_values: False
  output_name: "saa_BN_pool"
  hh_syn_name: "hh_syn_saa.csv"
  reruns: 10

- method: saa
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_sample_file: "../processed_data/full/hh_sample_ipu.csv"
  hh_seed_data: "../processed_data/full/hh_sample_ipu.csv"
  level: "hh"
  zone_field: "zone_id"
  considered_atts:
    - hhsize
    - hhinc
    - totalvehs
    - dwelltype
    - owndwell
  ordered_to_adjust_atts:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  last_adjustment_order:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  max_run_time: 15
  extra_rm_frac: 0.3
  randomly_add_last:
    - hhinc
  output_each_step: True
  add_name_for_step_output: "misszero"
  include_zero_cell_values: False
  output_name: "saa_seed_misszero"
  hh_syn_name: "hh_syn_saa.csv"
  reruns: 10

- method: saa
  hh_marg_file: "../processed_data/full/hh_marginals_ipu.csv"
  hh_sample_file: "../processed_data/full/hh_sample_ipu.csv"
  hh_seed_data: "../processed_data/full/hh_sample_ipu.csv"
  level: "hh"
  zone_field: "zone_id"
  considered_atts:
    - hhsize
    - hhinc
    - totalvehs
    - dwelltype
    - owndwell
  ordered_to_adjust_atts:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  last_adjustment_order:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  max_run_time: 15
  extra_rm_frac: 0.3
  randomly_add_last:
    - hhinc
  output_each_step: True
  add_name_for_step_output: "addzero"
  include_zero_cell_values: True
  output_name: "saa_seed_addzero"
  hh_syn_name: "hh_syn_saa.csv"
  reruns: 10