# - method: ipu
#   hh_marg_file: "../processed_data/full/hh_marginals_full.csv"
#   p_marg_file: "../processed_data/full/pp_full_marginals.csv"
#   hh_sample_file: "../processed_data/full/hh_sample_ipu.csv"
#   p_sample_file: "../processed_data/full/pp_sample_ipu.csv"
#   output_name: "ipu_full"
#   hh_syn_name: "hh_syn_ipu.csv"
#   pp_syn_name: "pp_syn_ipu.csv"
#   stats_name: "stats_ipu.csv"

- method: ipu
  hh_marg_file: "../processed_data/small/hh_marginals_small.csv"
  p_marg_file: "../processed_data/small/pp_small_marginals.csv"
  hh_sample_file: "../processed_data/small/hh_sample_ipu.csv"
  p_sample_file: "../processed_data/small/pp_sample_ipu.csv"
  output_name: "ipu_small"
  hh_syn_name: "hh_syn_ipu.csv"
  pp_syn_name: "pp_syn_ipu.csv"
  stats_name: "stats_ipu.csv"