- method: saa
  hh_marg_file: "../processed_data/small/hh_marginals_small.csv"
  hh_sample_file: "../processed_data/full/HH_pool.csv"
  level: "hh"
  zone_field: "zone_id"
  considered_atts:
    - hhsize
    - hhinc
    - totalvehs
    - dwelltype
    - owndwell
  ordered_to_adjust_atts:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  last_adjustment_order:
    - hhsize
    - totalvehs
    - hhinc
    - dwelltype
    - owndwell
  max_run_time: 10
  extra_rm_frac: 0.3
  randomly_add_last:
    - hhinc
  output_each_step: True
  add_name_for_step_output: "test"
  include_zero_cell_values: False
  output_name: "saa_small"
  hh_syn_name: "hh_syn_saa.csv"
  reruns: 2